name: Abaddon Zigbee2MQTT
version: "dev"
slug: abaddon_zigbee2mqtt
description: Custom Zigbee2MQTT - Zigbee to MQTT bridge with custom features
url: https://github.com/abaddon/zigbee2mqtt
arch:
  - aarch64
  - amd64
startup: application
boot: auto
map:
  - share:rw
  - config:rw
options:
  data_path: /config/zigbee2mqtt
  socat:
    enabled: false
    master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
    slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
    options: "-d -d"
    log: false
  mqtt: {}
  serial: {}
schema:
  data_path: str
  socat:
    enabled: bool
    master: str
    slave: str
    options: str
    log: bool
  mqtt:
    server: str?
    user: str?
    password: password?
    base_topic: str?
  serial:
    port: str?
    adapter: str?
ports:
  8080/tcp: 8099
ports_description:
  8080/tcp: Web interface (Zigbee2MQTT frontend)
backup: hot
homeassistant_api: true
hassio_api: true
hassio_role: default
init: false
devices:
  - /dev/ttyACM0
  - /dev/ttyUSB0
  - /dev/ttyUSB1
  - /dev/serial/by-id
udev: true
