name: Merge master to dev

on:
    push:
        branches:
            - master

jobs:
    merge-master-to-dev:
        runs-on: ubuntu-latest
        # Disabled for custom fork - typically not needed for manual branch management
        if: false
        steps:
            - uses: actions/checkout@v6
            - uses: devmasx/merge-branch@master
              with:
                  type: now
                  head_to_merge: master
                  target_branch: dev
                  message: 'chore: merge master to dev'
                  github_token: ${{ secrets.GITHUB_TOKEN }}
